### ISSUE TITLE
Is this a plugin for gephi waiting to happen?

### ISSUE THREAD

**Issue by Bazmundi** [megadix/jfcm#4]
Is this a code weekend from being a plugin to gephi graph editor?

Especially with the build it jython scripting, some interesting analysis opportunities.

Just brain storming ;)

**Comment by megadix** [comment]
Yeah it looks like a good fit.
It's a very long time since I don't improve JFCM, so I'm not sure how to do this integration... dare to contribute? ;-)

**Comment by Bazmundi** [comment]
Possibly. I also added it to gephi list of ideas. Might be a problem given
the current design of gephi does not allow traits to be added easily. It
might be deeper than shallow integration.

**Comment by Bazmundi** [comment]
Found https://github.com/ziqushru/JFCM-Design-App/blob/master/README.md which looks promising, uses JFCM but the application doesn't start for some reason.  An issue has been raised against that project.
