### ISSUE TITLE
For your information, JFCM mentioned in FCM paper

### ISSUE THREAD

**Issue by Bazmundi** [megadix/jfcm#5]
https://www.researchgate.net/publication/328218204

While the paper is FCM over time series, does the learning algorithm aspects make sense in the JFCM case?   Might depend on the converging versus non-converging angles si?

**Comment by megadix** [comment]
JFCM can be viewed as a bare "execution engine" for FCMs, thus it has no built-in advanced features like learning algorithms, UIs etc.
However I designed it to be very simple and extendable so it can easily be embedded in other projects, you can develop learning algorithms, import/export and so on.

Sorry I did not understand the last question:

> Might depend on the converging versus non-converging angles si?
